package it.cg.main.integration.mapper.enumerations;

public enum ENUMInternalCodeUnit {
	
	CODE_AS1("AS1"),
	CODE_AV1("AV1"),
	CODE_BP1("BP1"),
	CODE_COLL1("COLL1"),
	CODE_CRI1("CRI1"),
	CODE_EN1("EN1"),
	CODE_FUR1("FUR1"),
	CODE_IIP1("IIP1"),
	CODE_IM1("IM1"),
	CODE_INC1("INC1"),
	CODE_KAS1("KAS1"),
	CODE_RCA1("RCA1"),
	CODE_RCA11("RCA11"),//SOTTOCATEGORIA
	CODE_RCA12("RCA12"),//SOTTOCATEGORIA
	CODE_RCA14("RCA14"),//SOTTOCATEGORIA
	CODE_RCA15("RCA15"),//SOTTOCATEGORIA
	CODE_RCA16("RCA16"),//SOTTOCATEGORIA
	CODE_RCA17("RCA17"),//SOTTOCATEGORIA
	CODE_RCA2("RCA2"),//SOTTOCATEGORIA
	CODE_RCA3("RCA3"),//SOTTOCATEGORIA
	CODE_RCA4("RCA4"),//SOTTOCATEGORIA
	CODE_RCA5("RCA5"),//SOTTOCATEGORIA
	CODE_RCA6("RCA6"),//SOTTOCATEGORIA
	CODE_RCA7("RCA7"),//SOTTOCATEGORIA
	CODE_RCA8("RCA8"),//SOTTOCATEGORIA
	CODE_RCA9("RCA9"),//SOTTOCATEGORIA
	CODE_RCAR1("RCAR1"),//NON SO SE SOTTOCATEGORIA
	CODE_TG1("TG1"),//SOTTOCATEGORIA
	CODE_TG2("TG2"),//SOTTOCATEGORIA
	
	;
	
	private String value;

	ENUMInternalCodeUnit(String value) {
        this.value = value;
    }

    public String value() {
        return value;
    }

}
