package it.cg.main.dto.inbound;

import java.io.Serializable;
import java.util.List;

public class InboundWsFactorAssetInstanceDTO implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 3317128165155232047L;
	/**
	 * Attributi relativi a InboundWsAssetInstanceDTO
	 */
	private String n2aave;
	private String n2afon;
	private String n2alim;
	private List<String> n2bm;
	private String n2cbma;
	private String n2cbmp;
	private Integer n2cc;
	private Integer n2ceta;
	private Integer n2cf;
	private Integer n2cmar;
	private Integer n2cmod;
	private String n2cnas;
	private Integer n2crca;
	private Integer n2cris;
	private Integer n2crpr;
	private String n2csxm;
	private String n2ctpf;
	private List<String> n2cu;
	private List<String> n2cuas;
	private List<String> n2cupr;
	private String n2dich;
	private String n2dimm;
	private List<String> n2ftaa;
	private List<String> n2ftap;
	private Integer n2kw;
	private Integer n2mimm;
	private Integer n2peta;
	private String n2pnas;
	private Integer n2prca;
	private Integer n2pris;
	private Integer n2prpr;
	private Boolean n2psxm;
	private Boolean n2ptpf;
	private List<String> n2vfon;
	private Integer n2vval;
	private List<String> n2aavew;
	private Boolean n2alaut;
	private Boolean n2allr1;
	private Integer n2anacq;
	private Integer n2anrin;
	private List<String> n2antif;
	private Integer n2anucf;
	private Integer n2apimm;
	private Integer n2assic;
	private Integer n2assin;
	private List<String> n2bers;
	private Boolean n2bersp;
	private List<String> n2bombk;
	private Integer n2cluwr;
	private Integer n2cmarm;
	private Integer n2etav;
	private Integer n2evacq;
	private Integer n2kman;
	private List<String> n2kmann;
	private Integer n2mdanp;
	private Integer n2mdap;
	private List<String> n2mdpat;
	private Boolean n2mdph;
	private List<String> n2mdpr;
	private List<String> n2mdsc;
	private Integer n2mkmdl;
	private Boolean n2modr1;
	private List<String> n2nairb;
	private Integer n2ndriv;
	private Integer n2numab;
	private Integer n2numf;
	private Integer n2owanp;
	private Integer n2owap;
	private Boolean n2owmd;
	private List<String> n2owpat;
	private Boolean n2owph;
	private Boolean n2owppa;
	private List<String> n2owpr;
	private List<String> n2owsc;
	private List<String> n2parkn;
	private Integer n2primc;
	private List<String> n2promc;
	private String n2pvmd;
	private String n2pvow;
	private String n2pvrd1;
	private String n2pvrd2;
	private Integer n2r1anp;
	private Integer n2r2anp;
	private Integer n2rd1ap;
	private Integer n2rd1ca;
	private Integer n2rd1et;
	private String n2rd1na;
	private List<String> n2rd1pa;
	private List<String> n2rd1sc;
	private Integer n2rd2ap;
	private String n2rd2bd;
	private Integer n2rd2ca;
	private Integer n2rd2et;
	private List<String> n2rd2pa;
	private List<String> n2rd2sc;
	private List<String> n2regre;
	private Boolean n2rinnb;
	private List<String> n2rowmd;
	private List<String> n2rroad;
	private Integer n2seats;
	private Boolean n2sin1a;
	private List<String> n2sin3;
	private Integer n2sin3a;
	private List<String> n2sin6;
	private Integer n2sin6a;
	private Integer n2sin6p;
	private String n2tcarr;
	private List<String> n2ticar;
	private List<String> n2tipgu;
	private String n2tveic;
	private List<String> n2tvinc;
	private List<String> n2usove;
	private Integer n2valcm;
	private Integer n2valri;
	private Integer n2wcap ;
	private Boolean n3assi5;
	private Boolean n3clin1;
	private Boolean n3clin5;
	private List<String> n3conto;
	private Integer n3massa;
	private Integer n3ydage;
	private List<String> n4rowmd;
	private Integer sxtot;

}
